<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        DB::table('adventure_regions')->insert([
            [
                'slug' => 'greenwild-frontier',
                'name' => 'Greenwild Frontier',
                'description' => 'An overgrown frontier where small creatures guard ancient roots.',
                'visual_key' => 'region_greenwild',
                'min_level' => 1,
                'boss_unlock_victories' => 3,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'embercrag',
                'name' => 'Embercrag',
                'description' => 'A volcanic road of ash, iron and relentless heat.',
                'visual_key' => 'region_embercrag',
                'min_level' => 3,
                'boss_unlock_victories' => 4,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'moonfall-ruins',
                'name' => 'Moonfall Ruins',
                'description' => 'Silent ruins where moonlight wakes things that should be sleeping.',
                'visual_key' => 'region_moonfall',
                'min_level' => 5,
                'boss_unlock_victories' => 5,
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        $regions = DB::table('adventure_regions')->pluck('id', 'slug');

        DB::table('adventure_enemies')->insert([
            [
                'region_id' => $regions['greenwild-frontier'],
                'slug' => 'mossling',
                'name' => 'Mossling',
                'description' => 'A stubborn sprout-creature that attacks anything louder than rain.',
                'type' => 'normal',
                'visual_key' => 'enemy_mossling',
                'max_hp' => 55,
                'attack' => 7,
                'defense' => 3,
                'reward_gold' => 8,
                'reward_renown' => 3,
                'boss_reward_rarity' => null,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['greenwild-frontier'],
                'slug' => 'thorn-wolf',
                'name' => 'Thorn Wolf',
                'description' => 'Fast, territorial and covered in bramble-like fur.',
                'type' => 'elite',
                'visual_key' => 'enemy_thorn_wolf',
                'max_hp' => 95,
                'attack' => 12,
                'defense' => 6,
                'reward_gold' => 14,
                'reward_renown' => 6,
                'boss_reward_rarity' => null,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['greenwild-frontier'],
                'slug' => 'root-warden',
                'name' => 'Root Warden',
                'description' => 'An ancient guardian that has mistaken every traveler for an invader.',
                'type' => 'boss',
                'visual_key' => 'enemy_root_warden',
                'max_hp' => 220,
                'attack' => 18,
                'defense' => 10,
                'reward_gold' => 60,
                'reward_renown' => 25,
                'boss_reward_rarity' => 'rare',
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['embercrag'],
                'slug' => 'ash-crawler',
                'name' => 'Ash Crawler',
                'description' => 'A coal-black crawler that bursts from warm cracks in the road.',
                'type' => 'normal',
                'visual_key' => 'enemy_ash_crawler',
                'max_hp' => 105,
                'attack' => 14,
                'defense' => 7,
                'reward_gold' => 16,
                'reward_renown' => 7,
                'boss_reward_rarity' => null,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['embercrag'],
                'slug' => 'cinder-hound',
                'name' => 'Cinder Hound',
                'description' => 'A hunting beast that leaves a brief orange trail in the ash.',
                'type' => 'elite',
                'visual_key' => 'enemy_cinder_hound',
                'max_hp' => 165,
                'attack' => 21,
                'defense' => 10,
                'reward_gold' => 24,
                'reward_renown' => 11,
                'boss_reward_rarity' => null,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['embercrag'],
                'slug' => 'forge-tyrant',
                'name' => 'Forge Tyrant',
                'description' => 'A molten construct that treats the entire mountain as its forge.',
                'type' => 'boss',
                'visual_key' => 'enemy_forge_tyrant',
                'max_hp' => 360,
                'attack' => 30,
                'defense' => 15,
                'reward_gold' => 95,
                'reward_renown' => 40,
                'boss_reward_rarity' => 'rare',
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['moonfall-ruins'],
                'slug' => 'wisp-knight',
                'name' => 'Wisp Knight',
                'description' => 'An empty suit of armor kept moving by a pale wandering flame.',
                'type' => 'normal',
                'visual_key' => 'enemy_wisp_knight',
                'max_hp' => 170,
                'attack' => 23,
                'defense' => 12,
                'reward_gold' => 28,
                'reward_renown' => 12,
                'boss_reward_rarity' => null,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['moonfall-ruins'],
                'slug' => 'void-scholar',
                'name' => 'Void Scholar',
                'description' => 'A silent caster still studying a lesson that ended centuries ago.',
                'type' => 'elite',
                'visual_key' => 'enemy_void_scholar',
                'max_hp' => 245,
                'attack' => 32,
                'defense' => 14,
                'reward_gold' => 38,
                'reward_renown' => 18,
                'boss_reward_rarity' => null,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['moonfall-ruins'],
                'slug' => 'moonbound-colossus',
                'name' => 'Moonbound Colossus',
                'description' => 'A towering relic animated by a fractured lunar core.',
                'type' => 'boss',
                'visual_key' => 'enemy_moonbound_colossus',
                'max_hp' => 520,
                'attack' => 42,
                'defense' => 20,
                'reward_gold' => 150,
                'reward_renown' => 65,
                'boss_reward_rarity' => 'epic',
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        DB::table('adventure_objectives')->insert([
            [
                'region_id' => $regions['greenwild-frontier'],
                'slug' => 'greenwild-first-blood',
                'name' => 'First Blood',
                'description' => 'Defeat 1 Greenwild enemy.',
                'criteria_type' => 'region_victories',
                'threshold' => 1,
                'reward_gold' => 10,
                'reward_renown' => 5,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['greenwild-frontier'],
                'slug' => 'greenwild-trail-clear',
                'name' => 'Clear the Trail',
                'description' => 'Defeat 3 Greenwild enemies.',
                'criteria_type' => 'region_victories',
                'threshold' => 3,
                'reward_gold' => 20,
                'reward_renown' => 10,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['greenwild-frontier'],
                'slug' => 'greenwild-root-warden',
                'name' => 'Break the Old Guard',
                'description' => 'Defeat the Root Warden.',
                'criteria_type' => 'boss_victory',
                'threshold' => 1,
                'reward_gold' => 35,
                'reward_renown' => 20,
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['embercrag'],
                'slug' => 'embercrag-first-blood',
                'name' => 'Ash Walker',
                'description' => 'Defeat 1 Embercrag enemy.',
                'criteria_type' => 'region_victories',
                'threshold' => 1,
                'reward_gold' => 18,
                'reward_renown' => 8,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['embercrag'],
                'slug' => 'embercrag-trail-clear',
                'name' => 'Through the Heat',
                'description' => 'Defeat 4 Embercrag enemies.',
                'criteria_type' => 'region_victories',
                'threshold' => 4,
                'reward_gold' => 35,
                'reward_renown' => 15,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['embercrag'],
                'slug' => 'embercrag-forge-tyrant',
                'name' => 'Cool the Forge',
                'description' => 'Defeat the Forge Tyrant.',
                'criteria_type' => 'boss_victory',
                'threshold' => 1,
                'reward_gold' => 55,
                'reward_renown' => 28,
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['moonfall-ruins'],
                'slug' => 'moonfall-first-blood',
                'name' => 'Into the Ruins',
                'description' => 'Defeat 1 Moonfall enemy.',
                'criteria_type' => 'region_victories',
                'threshold' => 1,
                'reward_gold' => 28,
                'reward_renown' => 12,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['moonfall-ruins'],
                'slug' => 'moonfall-trail-clear',
                'name' => 'Quiet the Halls',
                'description' => 'Defeat 5 Moonfall enemies.',
                'criteria_type' => 'region_victories',
                'threshold' => 5,
                'reward_gold' => 50,
                'reward_renown' => 22,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'region_id' => $regions['moonfall-ruins'],
                'slug' => 'moonfall-colossus',
                'name' => 'Moonbreaker',
                'description' => 'Defeat the Moonbound Colossus.',
                'criteria_type' => 'boss_victory',
                'threshold' => 1,
                'reward_gold' => 90,
                'reward_renown' => 40,
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    public function down(): void
    {
        DB::table('adventure_objective_claims')->delete();
        DB::table('adventure_objectives')->delete();
        DB::table('adventure_combat_actions')->delete();
        DB::table('adventure_encounters')->delete();
        DB::table('adventure_region_progress')->delete();
        DB::table('adventure_profiles')->delete();
        DB::table('adventure_enemies')->delete();
        DB::table('adventure_regions')->delete();
    }
};
